name: simply_injector_example
description: Sample for Simply Injector.
version: 1.1.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  simply_injector:
    path: ..

dev_dependencies:
  test: any
